/**********************************************************************      
$Archive  : 00_TABLAS_DEPRECIACION_ORA.sql
$Revision : $      
$Author   : CAD      
$Modtime  : $       
$History  : $   Metodo de Reposicion (MR)   
**********************************************************************/  

/*
DROP TABLE MR_TB_LISTADO_MATERIAL_MANO_OBRA ;
DROP TABLE MR_TB_COMBINACION_USOS ;
DROP TABLE MR_TB_CLASIFICACION_USOS ;
DROP TABLE MR_TB_ACT_OBR_COD_FICHA_RES ;
DROP TABLE MR_TB_ACT_OBR_COD_FICHA_COM ;
DROP TABLE MR_TB_ACTIVIDAD_OBRA_MATERIAL ;
DROP TABLE MR_TB_PUNTAJE_DEPRECIACION ;

SELECT 'MR_TB_LISTADO_MATERIAL_MANO_OBRA' AS T,COUNT(1) AS C FROM MR_TB_LISTADO_MATERIAL_MANO_OBRA 
UNION 
SELECT 'MR_TB_COMBINACION_USOS' AS T,COUNT(1) AS C FROM MR_TB_COMBINACION_USOS 
UNION 
SELECT 'MR_TB_CLASIFICACION_USOS' AS T ,COUNT(1) AS C FROM MR_TB_CLASIFICACION_USOS 
UNION 
SELECT 'MR_TB_ACT_OBR_COD_FICHA_RES' AS T ,COUNT(1)AS C  FROM MR_TB_ACT_OBR_COD_FICHA_RES 
UNION 
SELECT 'MR_TB_ACT_OBR_COD_FICHA_COM' AS T ,COUNT(1)AS C FROM MR_TB_ACT_OBR_COD_FICHA_COM 
UNION 
SELECT 'MR_TB_ACTIVIDAD_OBRA_MATERIAL' AS T ,COUNT(1)AS C FROM MR_TB_ACTIVIDAD_OBRA_MATERIAL 
UNION 
SELECT 'MR_TB_PUNTAJE_DEPRECIACION' AS T ,COUNT(1)AS C FROM MR_TB_PUNTAJE_DEPRECIACION ;

EXPLAIN PLAN FOR
SELECT * 
FROM MR_TB_LISTADO_MATERIAL_MANO_OBRA g 
WHERE g.id_materiales = 'VEPE_45';

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

*/

--#TABLA
DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_table_exists
    FROM all_tables
    WHERE table_name = 'MR_TB_CLASIFICACION_USOS'
    AND owner = USER;

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '

		CREATE TABLE MR_TB_CLASIFICACION_USOS 
		(
			ID_USO 						NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			CODIGO_USO 					CHAR(3) NOT NULL ,
			GRUPO_ESTADO_CONSERVACION 	VARCHAR2(20) NOT NULL,
			GRUPO_USO_PRESUPUESTO 		VARCHAR2(25) NOT NULL,
			GRUPO_USO_CANTIDAD			NUMBER NULL,
			VIGENCIA 					NUMBER NULL,
			CONSTRAINT UK_CODIGO_USO_VIGENCIA UNIQUE (CODIGO_USO, VIGENCIA)
		) TABLESPACE TS_SIICDAT 
    
       ';
    END IF;
END;


/
--#TABLA
DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_table_exists
    FROM all_tables
    WHERE table_name = 'MR_TB_COMBINACION_USOS'
    AND owner = USER;

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '

		CREATE TABLE MR_TB_COMBINACION_USOS 
		(
			ID_COMBINACION 				NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			CODIGO_USO_PREDOMINANTE 	CHAR(3) NOT NULL,
			CODIGO_USO_01 				CHAR(3) NOT NULL,
			CODIGO_USO_02 				CHAR(3),  -- Opcional
			CODIGO_USO_03 				CHAR(3),  -- Opcional
			GRUPO_USO_PRESUPUESTO 		VARCHAR2(50) NOT NULL,
			VIGENCIA 					NUMBER NULL
		) TABLESPACE TS_SIICDAT 
    
       ';
    END IF;
END;

/
--ALTER TABLE MR_TB_COMBINACIONES_USOS ADD CONSTRAINT FK_CU_PRED   FOREIGN KEY (CODIGO_USO_PREDOMINANTE) REFERENCES MR_TB_CLASIFICACION_USOS(CODIGO_USO);
--ALTER TABLE MR_TB_COMBINACIONES_USOS ADD CONSTRAINT FK_CU_USO_01 FOREIGN KEY (CODIGO_USO_01) REFERENCES MR_TB_CLASIFICACION_USOS(CODIGO_USO);
--ALTER TABLE MR_TB_COMBINACIONES_USOS ADD CONSTRAINT FK_CU_USO_02 FOREIGN KEY (CODIGO_USO_02) REFERENCES MR_TB_CLASIFICACION_USOS(CODIGO_USO);
--ALTER TABLE MR_TB_COMBINACIONES_USOS ADD CONSTRAINT FK_CU_USO_03 FOREIGN KEY (CODIGO_USO_03) REFERENCES MR_TB_CLASIFICACION_USOS(CODIGO_USO);

DECLARE
    v_exists NUMBER;
BEGIN
    -- FK_CU_PRED
    SELECT COUNT(*) INTO v_exists
    FROM user_constraints
    WHERE constraint_name = 'FK_CU_PRED';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE MR_TB_COMBINACION_USOS 
            ADD CONSTRAINT FK_CU_PRED 
            FOREIGN KEY (CODIGO_USO_PREDOMINANTE, VIGENCIA) 
            REFERENCES MR_TB_CLASIFICACION_USOS(CODIGO_USO, VIGENCIA)';
    END IF;

    -- FK_CU_USO_01
    SELECT COUNT(*) INTO v_exists
    FROM user_constraints
    WHERE constraint_name = 'FK_CU_USO_01';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE MR_TB_COMBINACION_USOS 
            ADD CONSTRAINT FK_CU_USO_01 
            FOREIGN KEY (CODIGO_USO_01, VIGENCIA) 
            REFERENCES MR_TB_CLASIFICACION_USOS(CODIGO_USO, VIGENCIA)';
    END IF;

    -- FK_CU_USO_02
    SELECT COUNT(*) INTO v_exists
    FROM user_constraints
    WHERE constraint_name = 'FK_CU_USO_02';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE MR_TB_COMBINACION_USOS 
            ADD CONSTRAINT FK_CU_USO_02 
            FOREIGN KEY (CODIGO_USO_02, VIGENCIA) 
            REFERENCES MR_TB_CLASIFICACION_USOS(CODIGO_USO, VIGENCIA)';
    END IF;

    -- FK_CU_USO_03
    SELECT COUNT(*) INTO v_exists
    FROM user_constraints
    WHERE constraint_name = 'FK_CU_USO_03';

    IF v_exists = 0 THEN
        EXECUTE IMMEDIATE '
            ALTER TABLE MR_TB_COMBINACION_USOS 
            ADD CONSTRAINT FK_CU_USO_03 
            FOREIGN KEY (CODIGO_USO_03, VIGENCIA) 
            REFERENCES MR_TB_CLASIFICACION_USOS(CODIGO_USO, VIGENCIA)';
    END IF;
END;


/
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_indexes
  WHERE index_name = 'IDX_COMB_USOS_01_02_03';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_COMB_USOS_01_02_03 
                       ON MR_TB_COMBINACION_USOS(CODIGO_USO_01, CODIGO_USO_02, CODIGO_USO_03, VIGENCIA)';
  END IF;
END;



/
--#TABLA
DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_table_exists
    FROM all_tables
    WHERE table_name = 'MR_TB_ACT_OBR_COD_FICHA_RES'
    AND owner = USER;

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '

		CREATE TABLE MR_TB_ACT_OBR_COD_FICHA_RES 
		(
			ID_ACT_OBR_RES 				NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			ID_ACTIVIDAD_OBRA 			VARCHAR2(255) NOT NULL,
			DESCRIPCION_ACTIVIDAD_OBRA 	VARCHAR2(255) NOT NULL,
			CODIGO_FICHA 				CHAR(3) NOT NULL,
			VIGENCIA 					NUMBER NULL
		) TABLESPACE TS_SIICDAT 
    
       ';
    END IF;
END;
/
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_indexes
  WHERE index_name = 'IDX_ID_ACTIVIDAD_OBRA';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ID_ACTIVIDAD_OBRA ON MR_TB_ACT_OBR_COD_FICHA_RES(ID_ACTIVIDAD_OBRA, VIGENCIA)';
  END IF;
END;


/
--#TABLA
DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_table_exists
    FROM all_tables
    WHERE table_name = 'MR_TB_ACT_OBR_COD_FICHA_COM'
    AND owner = USER;

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '

		CREATE TABLE MR_TB_ACT_OBR_COD_FICHA_COM 
		(
			ID_ACT_OBR_COM 				NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			ID_ACTIVIDAD_OBRA 			VARCHAR2(255) NOT NULL,
			DESCRIPCION_ACTIVIDAD_OBRA 	VARCHAR2(255) NOT NULL,
			CODIGO_FICHA 				CHAR(3) NOT NULL,
			VIGENCIA 					NUMBER NULL
		) TABLESPACE TS_SIICDAT 
    
       ';
    END IF;
END;
/
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_indexes
  WHERE index_name = 'IDX_ID_ACTIVIDAD_OBRA_1';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ID_ACTIVIDAD_OBRA_1 ON MR_TB_ACT_OBR_COD_FICHA_COM(ID_ACTIVIDAD_OBRA, VIGENCIA)';
  END IF;
END;

/
--#TABLA
DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_table_exists
    FROM all_tables
    WHERE table_name = 'MR_TB_ACTIVIDAD_OBRA_MATERIAL'
    AND owner = USER;

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '

	CREATE TABLE MR_TB_ACTIVIDAD_OBRA_MATERIAL 
	(
		ID_ACT_OBRA_MAT 			NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		CAPITULO_OBRA 				VARCHAR2(250) NOT NULL,
		ID_ACTIVIDAD_OBRA 			VARCHAR2(250) NOT NULL,
		UNIDAD_MEDIDA_ACT_OBRA 		VARCHAR2(250) NOT NULL,
		ID_MATERIAL 				VARCHAR2(50)  NOT NULL,
		CANTIDAD_MATERIAL 			NUMBER(18, 2) DEFAULT 0.00,
		VIGENCIA 					NUMBER NULL
	) TABLESPACE TS_SIICDAT 
    
       ';
    END IF;
END;

/
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_indexes
  WHERE index_name = 'IDX_ID_MATERIAL_1';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_ID_MATERIAL_1 ON MR_TB_ACTIVIDAD_OBRA_MATERIAL(ID_MATERIAL, VIGENCIA)';
  END IF;
END;


/
--#TABLA
DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_table_exists
    FROM all_tables
    WHERE table_name = 'MR_TB_PUNTAJE_DEPRECIACION'
    AND owner = USER;

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '

	CREATE TABLE MR_TB_PUNTAJE_DEPRECIACION 
	(
		ID_PUNTAJE 							NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
		VARIABLE_CALIFICACION 				VARCHAR2(250) NOT NULL,
		CODIGO_FICHA 						CHAR(3) NOT NULL,
		PUNTAJE_CONSERVACION_RESIDENCIAL 	NUMBER(18, 2) DEFAULT 0.00,
		PUNTAJE_CONSERVACION_COMERCIAL 		NUMBER(18, 2) DEFAULT 0.00,
		PUNTAJE_CONSERVACION_INDUSTRIAL 	NUMBER(18, 2) DEFAULT 0.00,
		VIGENCIA 							NUMBER NULL
	) TABLESPACE TS_SIICDAT 
    
       ';
    END IF;
END;

/
DECLARE
    v_table_exists NUMBER := 0;
BEGIN
    SELECT COUNT(*)
    INTO v_table_exists
    FROM all_tables
    WHERE table_name = 'MR_TB_LISTADO_MATERIAL_MANO_OBRA'
    AND owner = USER;

    IF v_table_exists = 0 THEN
        EXECUTE IMMEDIATE '

        CREATE TABLE MR_TB_LISTADO_MATERIAL_MANO_OBRA 
		(
			ID 							NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
			ID_MATERIAL 				VARCHAR2(50),
			DESCRIPCION_MATERIAL 		VARCHAR2(255),
			UNIDAD_MEDIDA_MATERIAL 	    VARCHAR2(10),
			COSTO_UNITARIO_MATERIAL 	NUMBER(18, 2),
			FUENTE 						VARCHAR2(250),
			EDICION 					VARCHAR2(50),
			PAGINA 						VARCHAR2(50),
			VIGENCIA 					NUMBER NULL
        ) TABLESPACE TS_SIICDAT 
    
       ';
    END IF;
END;
/
--ALTER TABLE MR_TB_LISTADO_MATERIALES_MANO_OBRA ADD CONSTRAINT FK_ID_MATER   FOREIGN KEY (ID_MATERIALES) REFERENCES MR_TB_ACTIVIDAD_OBRA_MATERIALES(ID_MATERIALES);
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_indexes
  WHERE index_name = 'IDX_LISTADO_MATERIAL_ID';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_LISTADO_MATERIAL_ID ON MR_TB_LISTADO_MATERIAL_MANO_OBRA(ID_MATERIAL, VIGENCIA)';
  END IF;
END;