
DECLARE v_vigencia NUMBER := 2026;
BEGIN 

--TRUNCATE TABLE MR_TB_REGLA_PRELIMINAR;
--SELECT * FROM MR_TB_REGLA_PRELIMINAR WHERE TIPO_ACTIVIDAD = 2;
DELETE MR_TB_REGLA_PRELIMINAR WHERE TIPO_ACTIVIDAD = 2;

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_01',2,1,'ARMAZON_ESTRUCTURA IN (114, 115)','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_01',2,2,'ARMAZON_ESTRUCTURA IN (114, 115)','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_02',2,1,'ARMAZON_ESTRUCTURA = 114','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_02',2,2,'ARMAZON_ESTRUCTURA = 114','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_03',2,1,'ARMAZON_ESTRUCTURA = 115','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_03',2,2,'ARMAZON_ESTRUCTURA = 115','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_04',2,1,'ARMAZON_ESTRUCTURA = 115','((FRENTE*2)+(FONDO*2))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_04',2,2,'ARMAZON_ESTRUCTURA = 115','((FRENTE*2)+(FONDO*2))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_05',2,1,'ARMAZON_ESTRUCTURA IN (112, 113)','((FRENTE*2)+(FONDO*2))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_05',2,2,'ARMAZON_ESTRUCTURA IN (112, 113)','((FRENTE*2)+(FONDO*2))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_06',2,1,'ARMAZON_ESTRUCTURA = 114','((FRENTE*2)+(FONDO*2))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_06',2,2,'ARMAZON_ESTRUCTURA = 114','((FRENTE*2)+(FONDO*2))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_07',2,1,'ARMAZON_ESTRUCTURA = 111','((FRENTE*2)+(FONDO*2))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_07',2,2,'ARMAZON_ESTRUCTURA = 111','((FRENTE*2)+(FONDO*2))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_08',2,1,'ARMAZON_ESTRUCTURA IN (111, 112, 113)','(FRENTE*FONDO)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_08',2,2,'ARMAZON_ESTRUCTURA IN (111, 112, 113)','(FRENTE*FONDO)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_09',2,1,'ARMAZON_ESTRUCTURA IN (114, 115)','(FRENTE*FONDO)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_09',2,2,'ARMAZON_ESTRUCTURA IN (114, 115)','(FRENTE*FONDO)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_10',2,1,'ARMAZON_ESTRUCTURA IN (111, 112, 113, 114, 115)','AREA_USO','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_10',2,2,'ARMAZON_ESTRUCTURA IN (111, 112, 113, 114, 115)','AREA_TOTAL_CONSTRUIDA','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_11',2,1,'ARMAZON_ESTRUCTURA IN (112, 113, 114, 115)','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_11',2,2,'ARMAZON_ESTRUCTURA IN (112, 113, 114, 115)','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_12',2,1,'ARMAZON_ESTRUCTURA IN (112, 113, 114, 115)','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_12',2,2,'ARMAZON_ESTRUCTURA IN (112, 113, 114, 115)','1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_13',2,1,'ARMAZON_ESTRUCTURA IN (113, 114, 115)','((FRENTE)*(FONDO))*0.3','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('PRELIM_13',2,2,'ARMAZON_ESTRUCTURA IN (113, 114, 115)','((FRENTE)*(FONDO))*0.3','',2025);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_01',2,1,'ARMAZON_ESTRUCTURA IN (111, 112, 113, 114, 115)','CASE WHEN AREA_USO <=500 THEN ((ROUND(NVL(FRENTE,0)/3,0)+1)*0.3*0.25*NVL(FONDO,0))+((ROUND(NVL(FONDO,0)/3,0)+1)*0.3*0.25*NVL(FRENTE,0)) ELSE ((ROUND(NVL(FRENTE,0)/1,0)+1)*0.3*0.25*NVL(FONDO,0))+((ROUND(NVL(FONDO,0)/1,0)+1)*0.3*0.25*NVL(FRENTE,0))END','',2026);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_01',2,2,'ARMAZON_ESTRUCTURA IN (111, 112, 113, 114, 115)','CASE WHEN AREA_TOTAL_CONSTRUIDA <=500 THEN((ROUND(NVL(FRENTE,0)/3,0)+1)*0.3*0.25*NVL(FONDO,0))+((ROUND(NVL(FONDO,0)/3,0)+1)*0.3*0.25*NVL(FRENTE,0)) ELSE ((ROUND(NVL(FRENTE,0)/1,0)+1)*0.3*0.25*NVL(FONDO,0))+((ROUND(NVL(FONDO,0)/1,0)+1)*0.3*0.25*NVL(FRENTE,0))END','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_02',2,1,'ARMAZON_ESTRUCTURA = 115','CASE WHEN AREA_USO <=500 THEN ((ROUND(NVL(FRENTE,0)/4,0)+1)*0.3*0.3* NVL(FONDO,0))+((ROUND(NVL(FONDO,0)/4,0)+1)*0.3*0.3*NVL(FRENTE,0)) ELSE ((ROUND(NVL(FRENTE,0)/1,0)+1)*0.3*0.3* NVL(FONDO,0))+((ROUND(NVL(FONDO,0)/1,0)+1)*0.3*0.3*NVL(FRENTE,0))END','',2026);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_02',2,2,'ARMAZON_ESTRUCTURA = 115','CASE WHEN AREA_TOTAL_CONSTRUIDA <=500 THEN ((ROUND(NVL(FRENTE,0)/4,0)+1)*0.3*0.3* NVL(FONDO,0))+((ROUND(NVL(FONDO,0)/4,0)+1)*0.3*0.3*NVL(FRENTE,0)) ELSE ((ROUND(NVL(FRENTE,0)/1,0)+1)*0.3*0.3* NVL(FONDO,0))+((ROUND(NVL(FONDO,0)/1,0)+1)*0.3*0.3*NVL(FRENTE,0))END','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_03',2,1,'ARMAZON_ESTRUCTURA IN (112, 113, 114, 115)','CASE WHEN AREA_PRIMER_PISO <= 500 THEN (FRENTE * FONDO)*0.3 ELSE (FRENTE* FONDO)*0.6 END','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_03',2,2,'ARMAZON_ESTRUCTURA IN (112, 113, 114, 115)','CASE WHEN AREA_PRIMER_PISO <= 500 THEN (FRENTE * FONDO)*0.3 ELSE (FRENTE* FONDO)*0.6 END','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_04',2,1,'PISOS_ACABADOS = 231','(FRENTE * FONDO)*0.5','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_04',2,2,'PISOS_ACABADOS = 231','(FRENTE * FONDO)*0.5','',2025);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_05',2,1,
'ARMAZON_ESTRUCTURA IN (111, 112, 113, 114, 115)',
'
(
  CASE 
    WHEN AREA_USO <= 500 THEN ((ROUND(FRENTE / 3, 0) + 1) * 0.3 * 0.25 * FONDO) + ((ROUND(FONDO / 3, 0) + 1) * 0.3 * 0.25 * FRENTE)
    ELSE ((ROUND(FRENTE / 1, 0) + 1) * 0.3 * 0.25 * FONDO) + ((ROUND(FONDO / 1, 0) + 1) * 0.3 * 0.25 * FRENTE)
  END
)
+
(
  CASE 
    WHEN AREA_USO <= 500 THEN ((ROUND(FRENTE / 4, 0) + 1) * 0.3 * 0.3 * FONDO) + ((ROUND(FONDO / 4, 0) + 1) * 0.3 * 0.3 * FRENTE)
    ELSE ((ROUND(FRENTE, 0) + 1) * 0.3 * 0.3 * FONDO) + ((ROUND(FONDO, 0) + 1) * 0.3 * 0.3 * FRENTE)
  END
)','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_05',2,2,
'ARMAZON_ESTRUCTURA IN (111, 112, 113, 114, 115)',
'
(
  CASE 
    WHEN AREA_USO <= 500 THEN ((ROUND(FRENTE / 3, 0) + 1) * 0.3 * 0.25 * FONDO) + ((ROUND(FONDO / 3, 0) + 1) * 0.3 * 0.25 * FRENTE)
    ELSE ((ROUND(FRENTE / 1, 0) + 1) * 0.3 * 0.25 * FONDO) + ((ROUND(FONDO / 1, 0) + 1) * 0.3 * 0.25 * FRENTE)
  END
)
+
(
  CASE 
    WHEN AREA_TOTAL_CONSTRUIDA <= 500 THEN ((ROUND(FRENTE / 4, 0) + 1) * 0.3 * 0.3 * FONDO) + ((ROUND(FONDO / 4, 0) + 1) * 0.3 * 0.3 * FRENTE)
    ELSE ((ROUND(FRENTE, 0) + 1) * 0.3 * 0.3 * FONDO) + ((ROUND(FONDO, 0) + 1) * 0.3 * 0.3 * FRENTE)
  END
)','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('MURPÑ_07',2,1,
'(CUBIERTA_MUROS_ACABADOS IN (222, 223, 224, 225)',
'(FRENTE * FONDO) * ((N_PISOS + N_SOTANOS) - 1)','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('MURPÑ_07',2,2,
'(CUBIERTA_MUROS_ACABADOS IN (222, 223, 224, 225)',
'(FRENTE * FONDO) * ((N_PISOS + N_SOTANOS) - 1)','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('INS_GAC_09',2,1,
'(CUBIERTA_MUROS_ACABADOS IN (222, 223, 224, 225)',
'(FRENTE * FONDO) * ((N_PISOS + N_SOTANOS) - 1)','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('INS_GAC_09',2,1,
'(TAMAÑO_BAÑO IN (313, 314, 412, 413, 414)',
'
CASE
   WHEN (TAMAÑO_BAÑO = 311 OR TAMAÑO_BAÑO = 0 OR TAMAÑO_BAÑO IS NULL)
   THEN 0
   ELSE CASE
            WHEN AREA_USO <= 500
            THEN CEIL(N_BANOS / 3)
            ELSE N_UNIDADES_USO_PRINCIPAL
        END
END + N_COCINAS','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('INS_GAC_09',2,2,
'(TAMAÑO_BAÑO IN (313, 314, 412, 413, 414)',
'
CASE
   WHEN (TAMAÑO_BAÑO = 311 OR TAMAÑO_BAÑO = 0 OR TAMAÑO_BAÑO IS NULL)
   THEN 0
   ELSE CASE
            WHEN AREA_TOTAL_CONSTRUIDA <= 500
            THEN CEIL(N_BANOS / 3)
            ELSE N_UNIDADES_USO_PRINCIPAL
        END
END + N_COCINAS','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('INS_GAC_10',2,1,
'(TAMAÑO_BAÑO IN (313, 314, 412, 413, 414)',
'
CASE
   WHEN (TAMAÑO_BAÑO = 311 OR TAMAÑO_BAÑO = 0 OR TAMAÑO_BAÑO IS NULL)
   THEN 0
   ELSE CASE
            WHEN AREA_USO <= 500
            THEN CEIL(N_BANOS / 3)
            ELSE N_UNIDADES_USO_PRINCIPAL
        END
END + N_COCINAS','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('INS_GAC_10',2,2,
'(TAMAÑO_BAÑO IN (313, 314, 412, 413, 414)',
'
CASE
   WHEN (TAMAÑO_BAÑO = 311 OR TAMAÑO_BAÑO = 0 OR TAMAÑO_BAÑO IS NULL)
   THEN 0
   ELSE CASE
            WHEN AREA_TOTAL_CONSTRUIDA <= 500
            THEN CEIL(N_BANOS / 3)
            ELSE N_UNIDADES_USO_PRINCIPAL
        END
END + N_COCINAS','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('APARATOS_01',2,1,
'(TAMAÑO_BAÑO IN (313, 314, 412, 413, 414)',
'CASE
   WHEN (TAMAÑO_BAÑO = 311 OR TAMAÑO_BAÑO = 0 OR TAMAÑO_BAÑO IS NULL)
   THEN 0
   ELSE
      CASE
         WHEN AREA_USO <= 500
         THEN CEIL(N_BANOS / 3)
         ELSE N_UNIDADES_USO_PRINCIPAL
      END
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('APARATOS_01',2,2,
'(TAMAÑO_BAÑO IN (313, 314, 412, 413, 414)',
'CASE
   WHEN (TAMAÑO_BAÑO = 311 OR TAMAÑO_BAÑO = 0 OR TAMAÑO_BAÑO IS NULL)
   THEN 0
   ELSE
      CASE
         WHEN AREA_TOTAL_CONSTRUIDA <= 500
         THEN CEIL(N_BANOS / 3)
         ELSE N_UNIDADES_USO_PRINCIPAL
      END
END','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('APARATOS_02',2,1,
'(TAMAÑO_BAÑO IN (335)',
'CASE
   WHEN (TAMAÑO_BAÑO = 311 OR TAMAÑO_BAÑO = 0 OR TAMAÑO_BAÑO IS NULL)
   THEN 0
   ELSE
      CASE
         WHEN AREA_USO <= 500
         THEN CEIL(N_BANOS / 3)
         ELSE N_UNIDADES_USO_PRINCIPAL
      END
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('APARATOS_02',2,2,
'(TAMAÑO_BAÑO IN (335)',
'CASE
   WHEN (TAMAÑO_BAÑO = 311 OR TAMAÑO_BAÑO = 0 OR TAMAÑO_BAÑO IS NULL)
   THEN 0
   ELSE
      CASE
         WHEN AREA_TOTAL_CONSTRUIDA <= 500
         THEN CEIL(N_BANOS / 3)
         ELSE N_UNIDADES_USO_PRINCIPAL
      END
END','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ACENCH_06',2,1,'(CUBIERTA_MUROS_ACABADOS IN (223,224,225)','(FRENTE * FONDO) * ((N_PISOS + N_SOTANOS) - 1)','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ACENCH_06',2,2,'(CUBIERTA_MUROS_ACABADOS IN (223,224,225)','(FRENTE * FONDO) * ((N_PISOS + N_SOTANOS) - 1)','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ACENCH_10',2,1,'(CUBIERTA_MUROS_ACABADOS IN (223,224,225)','(FRENTE * FONDO) * ((N_PISOS + N_SOTANOS) - 1)','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ACENCH_10',2,2,'(CUBIERTA_MUROS_ACABADOS IN (223,224,225)','(FRENTE * FONDO) * ((N_PISOS + N_SOTANOS) - 1)','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_06',2,1,'ARMAZON_ESTRUCTURA = 111','(FRENTE*FONDO)*0.2','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_06',2,2,'ARMAZON_ESTRUCTURA = 111','(FRENTE*FONDO)*0.2','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_07',2,1,'ARMAZON_ESTRUCTURA IN (111, 115)','(FRENTE*FONDO)*0.1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_07',2,2,'ARMAZON_ESTRUCTURA IN (111, 115)','(FRENTE*FONDO)*0.1','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_08',2,1,'ARMAZON_ESTRUCTURA = 115','(FRENTE*FONDO)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_08',2,2,'ARMAZON_ESTRUCTURA = 115','(FRENTE*FONDO)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_09',2,1,'ARMAZON_ESTRUCTURA IN (112, 113)','((ROUND(FRENTE/4,0)+1) * 0.3 * 0.3* FONDO) + ((ROUND(FONDO/4,0)+1)*0.3*0.3* FRENTE)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_09',2,2,'ARMAZON_ESTRUCTURA IN (112, 113)','((ROUND(FRENTE/4,0)+1) * 0.3 * 0.3* FONDO) + ((ROUND(FONDO/4,0)+1)*0.3*0.3* FRENTE)','',2025);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_10',2,1,
'ARMAZON_ESTRUCTURA IN (113, 114, 115)',
'CASE 
    WHEN AREA_TIPO_UNIDAD_USO <= 45 
    THEN ((3*9*0.3*0.3) + (4*4*0.3*0.3)) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    WHEN AREA_TIPO_UNIDAD_USO > 45 AND AREA_TIPO_UNIDAD_USO <= 48 
    THEN ((4*9*0.3*0.3) + (5*4*0.3*0.3)) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    WHEN AREA_TIPO_UNIDAD_USO > 48 AND AREA_TIPO_UNIDAD_USO <= 64 
    THEN (16*3*0.3*0.3) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    WHEN AREA_TIPO_UNIDAD_USO > 64 AND AREA_TIPO_UNIDAD_USO <= 80 
    THEN ((10*3*0.3*0.3) + (8*5*0.3*0.3)) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    WHEN AREA_TIPO_UNIDAD_USO > 80 
    THEN ((10*4*0.3*0.3) + (11*4*0.3*0.3)) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    ELSE 0
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_10',2,2,
'ARMAZON_ESTRUCTURA IN (113, 114, 115)',
'CASE 
    WHEN AREA_TIPO_UNIDAD_USO <= 45 
    THEN ((3*9*0.3*0.3) + (4*4*0.3*0.3)) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    WHEN AREA_TIPO_UNIDAD_USO > 45 AND AREA_TIPO_UNIDAD_USO <= 48 
    THEN ((4*9*0.3*0.3) + (5*4*0.3*0.3)) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    WHEN AREA_TIPO_UNIDAD_USO > 48 AND AREA_TIPO_UNIDAD_USO <= 64 
    THEN (16*3*0.3*0.3) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    WHEN AREA_TIPO_UNIDAD_USO > 64 AND AREA_TIPO_UNIDAD_USO <= 80 
    THEN ((10*3*0.3*0.3) + (8*5*0.3*0.3)) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    WHEN AREA_TIPO_UNIDAD_USO > 80 
    THEN ((10*4*0.3*0.3) + (11*4*0.3*0.3)) * (N_UNIDADES_USO_PRINCIPAL / N_PISOS)

    ELSE 0
END','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_11',2,1,
'ARMAZON_ESTRUCTURA IN (114, 115)',
'CASE
    WHEN AREA_TIPO_UNIDAD_USO <= 45 
    THEN (10 * 0.3 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    WHEN AREA_TIPO_UNIDAD_USO > 45 AND AREA_TIPO_UNIDAD_USO <= 48
    THEN (12 * 0.3 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    WHEN AREA_TIPO_UNIDAD_USO > 48 AND AREA_TIPO_UNIDAD_USO <= 64
    THEN (9 * 0.5 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    WHEN AREA_TIPO_UNIDAD_USO > 64 AND AREA_TIPO_UNIDAD_USO <= 80
    THEN (15 * 0.8 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    WHEN AREA_TIPO_UNIDAD_USO > 80
    THEN (16 * 0.9 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    ELSE 0
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_11',2,2,
'ARMAZON_ESTRUCTURA IN (114, 115)',
'CASE
    WHEN AREA_TIPO_UNIDAD_USO <= 45 
    THEN (10 * 0.3 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    WHEN AREA_TIPO_UNIDAD_USO > 45 AND AREA_TIPO_UNIDAD_USO <= 48
    THEN (12 * 0.3 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    WHEN AREA_TIPO_UNIDAD_USO > 48 AND AREA_TIPO_UNIDAD_USO <= 64
    THEN (9 * 0.5 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    WHEN AREA_TIPO_UNIDAD_USO > 64 AND AREA_TIPO_UNIDAD_USO <= 80
    THEN (15 * 0.8 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    WHEN AREA_TIPO_UNIDAD_USO > 80
    THEN (16 * 0.9 * (N_UNIDADES_USO_PRINCIPAL / N_PISOS))

    ELSE 0
END','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_13',2,1,
'ARMAZON_ESTRUCTURA = 115',
'CASE
    WHEN (N_PISOS + N_SOTANOS) = 7 
    THEN (ROUND(FRENTE/4,0) + 1) * ((ROUND(FONDO/4,0) + 1) * 10)

    WHEN (N_PISOS + N_SOTANOS) > 7 AND (N_PISOS + N_SOTANOS) <= 8
    THEN (ROUND(FRENTE/4,0) + 1) * ((ROUND(FONDO/4,0) + 1) * 15)

    WHEN (N_PISOS + N_SOTANOS) > 8 AND (N_PISOS + N_SOTANOS) <= 9
    THEN (ROUND(FRENTE/4,0) + 1) * ((ROUND(FONDO/4,0) + 1) * 20)

    WHEN (N_PISOS + N_SOTANOS) > 9
    THEN (ROUND(FRENTE/4,0) + 1) * (ROUND(FONDO/4,0) + 1) * 25

    ELSE 0
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_13',2,2,
'ARMAZON_ESTRUCTURA = 115',
'CASE
    WHEN (N_PISOS + N_SOTANOS) = 7 
    THEN (ROUND(FRENTE/4,0) + 1) * ((ROUND(FONDO/4,0) + 1) * 10)

    WHEN (N_PISOS + N_SOTANOS) > 7 AND (N_PISOS + N_SOTANOS) <= 8
    THEN (ROUND(FRENTE/4,0) + 1) * ((ROUND(FONDO/4,0) + 1) * 15)

    WHEN (N_PISOS + N_SOTANOS) > 8 AND (N_PISOS + N_SOTANOS) <= 9
    THEN (ROUND(FRENTE/4,0) + 1) * ((ROUND(FONDO/4,0) + 1) * 20)

    WHEN (N_PISOS + N_SOTANOS) > 9
    THEN (ROUND(FRENTE/4,0) + 1) * (ROUND(FONDO/4,0) + 1) * 25

    ELSE 0
END','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_14',2,1,
'ARMAZON_ESTRUCTURA = 115',
'CASE
    WHEN (N_PISOS + N_SOTANOS) >= 7 AND (N_PISOS + N_SOTANOS) < 14
    THEN (1.5 * 2.3 * 0.15 * 4 * (N_PISOS + N_SOTANOS))

    WHEN (N_PISOS + N_SOTANOS) >= 15
    THEN (1.5 * 2.3 * 0.15 * 4 * 3 * (N_PISOS + N_SOTANOS))

    ELSE 0
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_14',2,2,
'ARMAZON_ESTRUCTURA = 115',
'CASE
    WHEN (N_PISOS + N_SOTANOS) >= 7 AND (N_PISOS + N_SOTANOS) < 14
    THEN (1.5 * 2.3 * 0.15 * 4 * (N_PISOS + N_SOTANOS))

    WHEN (N_PISOS + N_SOTANOS) >= 15
    THEN (1.5 * 2.3 * 0.15 * 4 * 3 * (N_PISOS + N_SOTANOS))

    ELSE 0
END','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_18',2,1,
'ARMAZON_ESTRUCTURA = 115',
'CASE
    WHEN (N_PISOS + N_SOTANOS) >= 7 
         AND (N_PISOS + N_SOTANOS) < 14
    THEN (1.5 * 2.3 * 0.15 * 4 * (N_PISOS + N_SOTANOS))

    WHEN (N_PISOS + N_SOTANOS) >= 15
    THEN (1.5 * 2.3 * 0.15 * 4 * 3 * (N_PISOS + N_SOTANOS))

    ELSE 0
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('EXC_RELL_CIM_18',2,2,
'ARMAZON_ESTRUCTURA = 115',
'CASE
    WHEN (N_PISOS + N_SOTANOS) >= 7 
         AND (N_PISOS + N_SOTANOS) < 14
    THEN (1.5 * 2.3 * 0.15 * 4 * (N_PISOS + N_SOTANOS))

    WHEN (N_PISOS + N_SOTANOS) >= 15
    THEN (1.5 * 2.3 * 0.15 * 4 * 3 * (N_PISOS + N_SOTANOS))

    ELSE 0
END','',v_vigencia);




INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ESTRUC_01',2,1,'ARMAZON_ESTRUCTURA = 111','((2.3*2*2*FRENTE)+(2.3*2*2*FONDO))+(2.3*3*8)*(N_PISOS+N_SOTANOS)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ESTRUC_01',2,2,'ARMAZON_ESTRUCTURA = 111','((2.3*2*2*FRENTE)+(2.3*2*2*FONDO))+(2.3*3*8)*(N_PISOS+N_SOTANOS)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ESTRUC_02',2,1,'ARMAZON_ESTRUCTURA = 112','((2.3*NVL(FRENTE,0)*2)+(2.3*NVL(FONDO,0)*2))*(NVL(N_PISOS,0)+NVL(N_SOTANOS,0))+(NVL(N_BAÑOS,0)*2.3*2)+(NVL(N_COCINAS,0)*2.3*2)+((NVL(N_ESPACIOS,0)+1)*2.3*2)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ESTRUC_02',2,2,'ARMAZON_ESTRUCTURA = 112','((2.3*NVL(FRENTE,0)*2)+(2.3*NVL(FONDO,0)*2))*(NVL(N_PISOS,0)+NVL(N_SOTANOS,0))+(NVL(N_BAÑOS,0)*2.3*2)+(NVL(N_COCINAS,0)*2.3*2)+((NVL(N_ESPACIOS,0)+1)*2.3*2)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ESTRUC_03',2,1,'ARMAZON_ESTRUCTURA = 113','((2.3*FRENTE*2)+(2.3*FONDO*2))*(N_PISOS+N_SOTANOS)+(N_BAÑOS*2.3*2)+(N_COCINAS*2.3*2)+((N_ESPACIOS+1)*2.3*2)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ESTRUC_03',2,2,'ARMAZON_ESTRUCTURA = 113','((2.3*FRENTE*2)+(2.3*FONDO*2))*(N_PISOS+N_SOTANOS)+(N_BAÑOS*2.3*2)+(N_COCINAS*2.3*2)+((N_ESPACIOS+1)*2.3*2)','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ESTRUC_04',2,1,'NVL(N_SOTANOS,0) = 0 AND ARMAZON_ESTRUCTURA IN (114,115)','((ROUND(NVL(FRENTE,0)/4,0)+1) * (ROUND(NVL(FONDO,0)/4,0)+1) * 0.3 * 0.3 * 2.3 * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0)))','',2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ESTRUC_04',2,2,'NVL(N_SOTANOS,0) = 0 AND ARMAZON_ESTRUCTURA IN (114,115)','((ROUND(NVL(FRENTE,0)/4,0)+1) * (ROUND(NVL(FONDO,0)/4,0)+1) * 0.3 * 0.3 * 2.3 * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0)))','',2025);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_05', 2, 1,'N_SOTANOS = 1 AND ARMAZON_ESTRUCTURA IN (114,115)','((ROUND(NVL(FRENTE,0)/4,0)+1) * (ROUND(NVL(FONDO,0)/4,0)+1) * 0.4 * 0.4 * 2.3) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0))','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_05', 2, 2,'N_SOTANOS = 1 AND ARMAZON_ESTRUCTURA IN (114,115)','((ROUND(NVL(FRENTE,0)/4,0)+1) * (ROUND(NVL(FONDO,0)/4,0)+1) * 0.4 * 0.4 * 2.3) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0))','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_06', 2, 1,'N_SOTANOS >= 2 AND ARMAZON_ESTRUCTURA IN (114,115)','((ROUND(NVL(FRENTE,0)/4,0)+1) * (ROUND(NVL(FONDO,0)/4,0)+1) * 0.5 * 0.5 * 3) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0))','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_06', 2, 2,'N_SOTANOS >= 2 AND ARMAZON_ESTRUCTURA IN (114,115)','((ROUND(NVL(FRENTE,0)/4,0)+1) * (ROUND(NVL(FONDO,0)/4,0)+1) * 0.5 * 0.5 * 3) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0))','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_07', 2, 1,'ARMAZON_ESTRUCTURA IN (113,114,115) AND NVL(N_PISOS,0) >= 6','CASE WHEN NVL( NVL(AREA_TOTAL_CONSTRUIDA, AREA_USO), 0) < 1500 THEN 13*1.3*0.25*0.18*(NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1)ELSE 13*2*0.25*0.18*2*(NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1) END','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_07', 2, 2,'ARMAZON_ESTRUCTURA IN (113,114,115) AND NVL(N_PISOS,0) >= 6','CASE WHEN NVL( NVL(AREA_TOTAL_CONSTRUIDA, AREA_USO), 0) < 1500 THEN 13*1.3*0.25*0.18*(NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1) ELSE 13*2*0.25*0.18*2*(NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1) END','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_08', 2, 1,'N_SOTANOS = 0 AND ARMAZON_ESTRUCTURA IN (113,114,115)','(NVL(FRENTE,0)*NVL(FONDO,0)) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_08', 2, 2,'N_SOTANOS = 0 AND ARMAZON_ESTRUCTURA IN (113,114,115)','(NVL(FRENTE,0)*NVL(FONDO,0)) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_09', 2, 1,'N_SOTANOS = 1 AND ARMAZON_ESTRUCTURA IN (113,114,115)','(NVL(FRENTE,0)*NVL(FONDO,0)) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_09', 2, 2,'N_SOTANOS = 1 AND ARMAZON_ESTRUCTURA IN (113,114,115)','(NVL(FRENTE,0)*NVL(FONDO,0)) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_10', 2, 1,'N_SOTANOS >= 2 AND ARMAZON_ESTRUCTURA IN (113,114,115)','(NVL(FRENTE,0)*NVL(FONDO,0)) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_10', 2, 2,'N_SOTANOS >= 2 AND ARMAZON_ESTRUCTURA IN (113,114,115)','(NVL(FRENTE,0)*NVL(FONDO,0)) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0)-1)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_11', 2, 1,'ARMAZON_ESTRUCTURA IN (112,113,114)','NVL(FRENTE,0)*NVL(FONDO,0)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_11', 2, 2,'ARMAZON_ESTRUCTURA IN (112,113,114)','NVL(FRENTE,0)*NVL(FONDO,0)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_12', 2, 1,'ARMAZON_ESTRUCTURA = 115','NVL(FRENTE,0)*NVL(FONDO,0)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_12', 2, 2,'ARMAZON_ESTRUCTURA = 115','NVL(FRENTE,0)*NVL(FONDO,0)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_13', 2, 1,'ARMAZON_ESTRUCTURA IN (114,115)','(CASE
WHEN NVL(AREA_TIPO_UNIDAD_USO,0) <= 48 THEN (3*9*0.3*0.3 + 5*4*0.3*0.3)
WHEN NVL(AREA_TIPO_UNIDAD_USO,0) > 48 AND NVL(AREA_TIPO_UNIDAD_USO,0) <= 64 THEN (16*3*0.3*0.3)
WHEN NVL(AREA_TIPO_UNIDAD_USO,0) > 64 AND NVL(AREA_TIPO_UNIDAD_USO,0) <= 80 THEN (10*3*0.3*0.3 + 8*5*0.3*0.3)
WHEN NVL(AREA_TIPO_UNIDAD_USO,0) > 80 THEN (10*4*0.3*0.3 + 11*4*0.3*0.3) ELSE 0 END)* (NVL(N_UNIDADES_USO_PRINCIPAL,0) / NULLIF(NVL(N_PISOS,0),0))* (NVL(N_PISOS,0)+NVL(N_SOTANOS,0))','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES
('ESTRUC_13', 2, 2,'ARMAZON_ESTRUCTURA IN (114,115)','(CASE
WHEN NVL(AREA_TIPO_UNIDAD_USO,0) <= 48 THEN (3*9*0.3*0.3 + 5*4*0.3*0.3)
WHEN NVL(AREA_TIPO_UNIDAD_USO,0) > 48 AND NVL(AREA_TIPO_UNIDAD_USO,0) <= 64 THEN (16*3*0.3*0.3) WHEN NVL(AREA_TIPO_UNIDAD_USO,0) > 64 AND NVL(AREA_TIPO_UNIDAD_USO,0) <= 80 THEN (10*3*0.3*0.3 + 8*5*0.3*0.3)
WHEN NVL(AREA_TIPO_UNIDAD_USO,0) > 80 THEN (10*4*0.3*0.3 + 11*4*0.3*0.3) ELSE 0 END) * (NVL(N_UNIDADES_USO_PRINCIPAL,0) / NULLIF(NVL(N_PISOS,0),0)) * (NVL(N_PISOS,0)+NVL(N_SOTANOS,0))','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_20', 2, 1,'ARMAZON_ESTRUCTURA = 116','(NVL(N_BANOS,0)*2.3*2) + (NVL(N_COCINAS,0)*2.3*2) + ((NVL(N_ESPACIOS,0)+1)*2.3*2) + (((2.3*NVL(FRENTE,0)*2) + (2.3*NVL(FONDO,0)*2)) * NVL(N_SOTANOS,0))','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_20', 2, 2,'ARMAZON_ESTRUCTURA = 116','(NVL(N_BANOS,0)*2.3*2) + (NVL(N_COCINAS,0)*2.3*2) + ((NVL(N_ESPACIOS,0)+1)*2.3*2) + (((2.3*NVL(FRENTE,0)*2) + (2.3*NVL(FONDO,0)*2)) * NVL(N_SOTANOS,0))','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_21', 2, 1,'ARMAZON_ESTRUCTURA IN (114,115)','CASE WHEN NVL(N_SOTANOS,0) = 1 THEN ((3.5*0.3*NVL(FRENTE,0)*2) + (3.5*0.3*NVL(FONDO,0)*2)) * NVL(N_SOTANOS,0) WHEN NVL(N_SOTANOS,0) >= 2 THEN ((10*0.3*NVL(FRENTE,0)*2) + (10*0.3*NVL(FONDO,0)*2)) * NVL(N_SOTANOS,0) ELSE 0 END','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_21', 2, 2,'ARMAZON_ESTRUCTURA IN (114,115)','CASE WHEN NVL(N_SOTANOS,0) = 1 THEN ((3.5*0.3*NVL(FRENTE,0)*2) + (3.5*0.3*NVL(FONDO,0)*2)) * NVL(N_SOTANOS,0) WHEN NVL(N_SOTANOS,0) >= 2 THEN ((10*0.3*NVL(FRENTE,0)*2) + (10*0.3*NVL(FONDO,0)*2)) * NVL(N_SOTANOS,0) ELSE 0 END','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_25', 2, 1,'ARMAZON_ESTRUCTURA IN (114,115,117)','CASE WHEN ARMAZON_ESTRUCTURA = 117 THEN (NVL(N_BANOS,0)*2.3*2) + (NVL(N_COCINAS,0)*2.3*2) + ((NVL(N_ESPACIOS,0)+1)*2.3*2) WHEN NVL(N_SOTANOS,0) = 1 THEN 2 * (NVL(FONDO,0)*4*4*NVL(N_SOTANOS,0))WHEN NVL(N_SOTANOS,0) >= 2 THEN 2 * (NVL(FONDO,0)*4*8*NVL(N_SOTANOS,0))ELSE 0 END','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_25', 2, 2,'ARMAZON_ESTRUCTURA IN (114,115,117)','CASE WHEN ARMAZON_ESTRUCTURA = 117 THEN (NVL(N_BANOS,0)*2.3*2) + (NVL(N_COCINAS,0)*2.3*2) + ((NVL(N_ESPACIOS,0)+1)*2.3*2) WHEN NVL(N_SOTANOS,0) = 1 THEN 2 * (NVL(FONDO,0)*4*4*NVL(N_SOTANOS,0))WHEN NVL(N_SOTANOS,0) >= 2 THEN 2 * (NVL(FONDO,0)*4*8*NVL(N_SOTANOS,0))ELSE 0 END','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_26', 2, 1,'ARMAZON_ESTRUCTURA IN (116,117)','((2.3*NVL(FRENTE,0)*2) + (2.3*NVL(FONDO,0)*2)) * NVL(N_PISOS,0)','', 2025);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES('ESTRUC_26', 2, 2,'ARMAZON_ESTRUCTURA IN (116,117)','((2.3*NVL(FRENTE,0)*2) + (2.3*NVL(FONDO,0)*2)) * NVL(N_PISOS,0)','', 2025);

--RAFA------------------------
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_03',2,1,'CUBIERTA_MUROS_ACABADOS IN (223, 224, 225)','CASE WHEN ESTRATO = 4 THEN N_ESPACIOS * 3.5 * 2 ELSE 0 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_03',2,2,'CUBIERTA_MUROS_ACABADOS IN (223, 224, 225)','CASE WHEN ESTRATO = 4 THEN N_ESPACIOS * 3.5 * 2 ELSE 0 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_04',2,1,'CUBIERTA_MUROS_ACABADOS IN (223, 224, 225)','CASE WHEN ESTRATO IN (5, 6) THEN N_ESPACIOS ELSE 0 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_04',2,2,'CUBIERTA_MUROS_ACABADOS IN (223, 224, 225)','CASE WHEN ESTRATO IN (5, 6) THEN N_ESPACIOS ELSE 0 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_05',2,1,'MUROS_ESTRUCTURA IN (121, 122, 123)','2.3 * 0.7 * (N_ESPACIOS + N_BAÑOS)','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_05',2,2,'MUROS_ESTRUCTURA IN (121, 122, 123)','2.3 * 0.7 * (N_ESPACIOS + N_BAÑOS)','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_06',2,1,'MUROS_ESTRUCTURA IN (124)','N_ESPACIOS + N_BAÑOS + N_COCINAS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_06',2,2,'MUROS_ESTRUCTURA IN (124)','N_ESPACIOS + N_BAÑOS + N_COCINAS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_07',2,1,'MUROS_ESTRUCTURA IN (125)','CASE WHEN ESTRATO BETWEEN 1 AND 3 THEN N_ESPACIOS + N_BAÑOS ELSE N_ESPACIOS + N_BAÑOS + N_COCINAS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_07',2,2,'MUROS_ESTRUCTURA IN (125)','CASE WHEN ESTRATO BETWEEN 1 AND 3 THEN N_ESPACIOS + N_BAÑOS ELSE N_ESPACIOS + N_BAÑOS + N_COCINAS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_11',2,1,'MOBILIARIO_BAÑO IN (333,334,335)','N_BAÑOS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_11',2,2,'MOBILIARIO_BAÑO IN (333,334,335)','N_BAÑOS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_12',2,1,'MOBILIARIO_COCINA IN (433)','N_COCINAS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MAD_12',2,2,'MOBILIARIO_COCINA IN (433)','N_COCINAS','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_01',2,1,'FACHADA_ACABADOS IN (215)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_01',2,2,'FACHADA_ACABADOS IN (215)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_02',2,1,'FACHADA_ACABADOS IN (212, 213)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_02',2,2,'FACHADA_ACABADOS IN (212, 213)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_03',2,1,'FACHADA_ACABADOS IN (213)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_03',2,2,'FACHADA_ACABADOS IN (213)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_04',2,1,'FACHADA_ACABADOS IN (214)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_04',2,2,'FACHADA_ACABADOS IN (214)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_09',2,1,'ARMAZON_ESTRUCTURA IN (115,116,117)','CASE WHEN (N_PISOS + N_SOTANOS)>=7 AND (N_PISOS + N_SOTANOS)<14 THEN 1 WHEN (N_PISOS + N_SOTANOS)>=15 THEN 3 ELSE 0 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CARP_MET_09',2,2,'ARMAZON_ESTRUCTURA IN (115,116,117)','CASE WHEN (N_PISOS + N_SOTANOS)>=7 AND (N_PISOS + N_SOTANOS)<14 THEN 1 WHEN (N_PISOS + N_SOTANOS)>=15 THEN 3 ELSE 0 END','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_01',2,1,'MUROS_ESTRUCTURA IN (121, 122, 123, 124, 125)','N_ESPACIOS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_01',2,2,'MUROS_ESTRUCTURA IN (121, 122, 123, 124, 125)','N_ESPACIOS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_03',2,1,'FACHADA_ACABADOS IN (214)','2','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_03',2,2,'FACHADA_ACABADOS IN (214)','2','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_04',2,1,'FACHADA_ACABADOS IN (215)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 3 ELSE 3 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_04',2,2,'FACHADA_ACABADOS IN (215)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 3 ELSE 3 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_05',2,1,'FACHADA_ACABADOS IN (211, 212)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_05',2,2,'FACHADA_ACABADOS IN (211, 212)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_06',2,1,'FACHADA_ACABADOS IN (213)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_06',2,2,'FACHADA_ACABADOS IN (213)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL ELSE 1 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_07',2,1,'MOBILIARIO_BAÑO  IN (331, 332, 333, 334, 335)','N_BAÑOS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_07',2,2,'MOBILIARIO_BAÑO  IN (331, 332, 333, 334, 335)','N_BAÑOS','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_09',2,1,'FACHADA_ACABADOS  IN (212, 213, 214, 215)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 3 ELSE 3 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CERRA_09',2,2,'FACHADA_ACABADOS  IN (212, 213, 214, 215)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 3 ELSE 3 END','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_01',2,1,
'FACHADA_ACABADOS  IN (211)',
'CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 1 * (N_PISOS + N_SOTANOS)
  ELSE 1.5 * 1.5 * 1 * (N_PISOS + N_SOTANOS)
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_01',2,2,
'FACHADA_ACABADOS  IN (211)',
'CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 1 * (N_PISOS + N_SOTANOS)
  ELSE 1.5 * 1.5 * 1 * (N_PISOS + N_SOTANOS)
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_02',2,1,'FACHADA_ACABADOS  IN (212)','CASE WHEN AREA_USO >= 500 THEN 1.2 * 1.2 * 2 * (N_PISOS + N_SOTANOS) ELSE 1.2 * 1.2 * 2 * (N_PISOS + N_SOTANOS) END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_02',2,2,'FACHADA_ACABADOS  IN (212)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN 1.2 * 1.2 * 2 * (N_PISOS + N_SOTANOS) ELSE 1.2 * 1.2 * 2 * (N_PISOS + N_SOTANOS) END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_03',2,1,'FACHADA_ACABADOS  IN (213)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 2 * N_PISOS ELSE 1.5 * 1.5 * 3 * N_PISOS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_03',2,2,'FACHADA_ACABADOS  IN (213)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 2 * N_PISOS ELSE 1.5 * 1.5 * 3 * N_PISOS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_04',2,1,'FACHADA_ACABADOS  IN (215)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 5 * (N_PISOS + N_SOTANOS) ELSE 1.5 * 1.5 * 5 * (N_PISOS + N_SOTANOS) END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_04',2,2,'FACHADA_ACABADOS  IN (215)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 5 * (N_PISOS + N_SOTANOS) ELSE 1.5 * 1.5 * 5 * (N_PISOS + N_SOTANOS) END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_05',2,1,'FACHADA_ACABADOS  IN (214)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 4 * N_PISOS ELSE 1.5 * 1.5 * 2 * N_PISOS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_05',2,2,'FACHADA_ACABADOS  IN (214)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 4 * N_PISOS ELSE 1.5 * 1.5 * 2 * N_PISOS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_06',2,1,'FACHADA_ACABADOS  IN (212)','CASE WHEN AREA_USO >= 500 THEN 1.2 * 1.2 * 2 * (N_PISOS + N_SOTANOS) ELSE 1.2 * 1.2 * 2 * (N_PISOS + N_SOTANOS) END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_06',2,2,'FACHADA_ACABADOS  IN (212)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN 1.2 * 1.2 * 2 * (N_PISOS + N_SOTANOS) ELSE 1.2 * 1.2 * 2 * (N_PISOS + N_SOTANOS) END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_07',2,1,'FACHADA_ACABADOS  IN (213)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 2 * N_PISOS ELSE 1.5 * 1.5 * 3 * N_PISOS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_07',2,2,'FACHADA_ACABADOS  IN (213)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 2 * N_PISOS ELSE 1.5 * 1.5 * 3 * N_PISOS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_08',2,1,'FACHADA_ACABADOS  IN (214)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 4 * N_PISOS ELSE 1.5 * 1.5 * 2 * N_PISOS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_08',2,2,'FACHADA_ACABADOS  IN (214)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 4 * N_PISOS ELSE 1.5 * 1.5 * 2 * N_PISOS END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_09',2,1,'FACHADA_ACABADOS  IN (215)','CASE WHEN AREA_USO >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 5 * (N_PISOS + N_SOTANOS) ELSE 1.5 * 1.5 * 5 * (N_PISOS + N_SOTANOS) END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('VENT_09',2,2,'FACHADA_ACABADOS  IN (215)','CASE WHEN AREA_TOTAL_CONSTRUIDA >= 500 THEN N_UNIDADES_USO_PRINCIPAL * 1.5 * 1.5 * 5 * (N_PISOS + N_SOTANOS) ELSE 1.5 * 1.5 * 5 * (N_PISOS + N_SOTANOS) END','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_01',2,1,'CUBIERTA_ESTRUCTURA  IN (134, 136)','FRENTE','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_01',2,2,'CUBIERTA_ESTRUCTURA  IN (134, 136)','FRENTE','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_02',2,1,'CUBIERTA_ESTRUCTURA  IN (133, 134, 135, 136)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_02',2,2,'CUBIERTA_ESTRUCTURA  IN (133, 134, 135, 136)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_03',2,1,'CUBIERTA_ESTRUCTURA  IN (131)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_03',2,2,'CUBIERTA_ESTRUCTURA  IN (131)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_04',2,1,'CUBIERTA_ESTRUCTURA  IN (132)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_04',2,2,'CUBIERTA_ESTRUCTURA  IN (132)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_05',2,1,'CUBIERTA_ESTRUCTURA  IN (136)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_05',2,2,'CUBIERTA_ESTRUCTURA  IN (136)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_06',2,1,'CUBIERTA_ESTRUCTURA  IN (134)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_06',2,2,'CUBIERTA_ESTRUCTURA  IN (134)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_10',2,1,'CUBIERTA_ESTRUCTURA  IN (133, 135)','FRENTE * FONDO','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('CUBIMP_10',2,2,'CUBIERTA_ESTRUCTURA  IN (133, 135)','FRENTE * FONDO','',v_vigencia);


INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_01',2,1,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6',
'ROUND(CASE 
      WHEN ESTRATO IN (1,2,3) THEN (N_UNIDADES_USO_PRINCIPAL / 3) * 2
      WHEN ESTRATO = 4 THEN N_UNIDADES_USO_PRINCIPAL * 2
      WHEN ESTRATO IN (5,6) THEN N_UNIDADES_USO_PRINCIPAL * 2
      ELSE ROUND(FRENTE / 10, 0)
    END, 0)','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_01',2,2,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6',
'ROUND(CASE 
      WHEN ESTRATO IN (1,2,3) THEN (N_UNIDADES_USO_PRINCIPAL / 3) * 2
      WHEN ESTRATO = 4 THEN N_UNIDADES_USO_PRINCIPAL * 2
      WHEN ESTRATO IN (5,6) THEN N_UNIDADES_USO_PRINCIPAL * 2
      ELSE ROUND(FRENTE / 10, 0)
    END, 0)','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_02',2,1,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6',
'CASE 
  WHEN N_PISOS = 6 THEN ROUND(((FRENTE * 2) + (FONDO * 2)) * 20, 0)
  WHEN N_PISOS > 6 AND N_PISOS <= 8 THEN ROUND(((FRENTE * 2) + (FONDO * 2)) * 12, 0)
  WHEN N_PISOS > 8 THEN ROUND(((FRENTE * 2) + (FONDO * 2)) * 5.5, 0)
  ELSE 0
END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_02',2,2,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6',
'CASE 
  WHEN N_PISOS = 6 THEN ROUND(((FRENTE * 2) + (FONDO * 2)) * 20, 0)
  WHEN N_PISOS > 6 AND N_PISOS <= 8 THEN ROUND(((FRENTE * 2) + (FONDO * 2)) * 12, 0)
  WHEN N_PISOS > 8 THEN ROUND(((FRENTE * 2) + (FONDO * 2)) * 5.5, 0)
  ELSE 0
END','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_03',2,1,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6',
'ROUND((FRENTE * 2) + (FONDO * 2), 0)','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_03',2,2,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6',
'ROUND((FRENTE * 2) + (FONDO * 2), 0)','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_04',2,1,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6',
'(((ROUND(FRENTE, 0)) * 2) + ((ROUND(FONDO, 0)) * 3)) * 1.5','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_04',2,2,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6',
'(((ROUND(FRENTE, 0)) * 2) + ((ROUND(FONDO, 0)) * 3)) * 1.5','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_05',2,1,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6','6','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('OBEX_05',2,2,
'FACHADA_ACABADOS IN (212, 213, 214, 215) AND N_PISOS >= 6','6','',v_vigencia);

INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ASE_GEN_01',2,1,
'MUROS_ESTRUCTURA IN (121, 122, 123, 124, 125)',
'CASE WHEN AREA_USO >= 1500 THEN AREA_USO ELSE 0 END','',v_vigencia);
INSERT INTO MR_TB_REGLA_PRELIMINAR (ID_ACTIVIDAD_OBRA, TIPO_ACTIVIDAD, TIPO_PRESUPUESTO, CONDICION, FORMULA, DESCRIPCION_REGLA, VIGENCIA) VALUES ('ASE_GEN_01',2,2,
'MUROS_ESTRUCTURA IN (212, 213, 214, 215) AND N_PISOS >= 6',
'CASE WHEN AREA_USO >= 1500 THEN AREA_USO ELSE 0 END','',v_vigencia);


COMMIT;



END;
